# General
# ------------------------------------------------
PLAN__TERM_TIMEOUT='10'
PLAN__ENABLE_CACHE='false'
PLAN__KEEP_CACHE='never'
PLAN__ENABLE_VCACHE='false'
PLAN__KEEP_VCACHE='never'

# Modules
# ------------------------------------------------
PLAN__MODULES_DEFAULT_TITLE='Running Module'
PLAN__MODULES_ENFORCE_TITLE='false'
PLAN__MODULES_DEFAULT_CMD=''
PLAN__MODULES_LOG_DIR=''
PLAN__MODULES_LOG_KEEP='false'

# State
# ------------------------------------------------
PLAN__STATE_TRACK='true'
PLAN__STATE_ID=''
PLAN__STATE_HASH_ID='true'
PLAN__STATE_DIR=''

# Logging
# ------------------------------------------------
# PLAN__LOGGING_LEVEL='INFO'
# PLAN__LOGGING_CALLER_LEVEL='ERROR'
PLAN__LOGGING_ERROR_PREFIX=''
PLAN__LOGGING_ERROR_COLOR='1'
PLAN__LOGGING_WARN_PREFIX=''
PLAN__LOGGING_WARN_COLOR='3'
PLAN__LOGGING_INFO_PREFIX=''
PLAN__LOGGING_INFO_COLOR='4'
PLAN__LOGGING_DEBUG_PREFIX=''
PLAN__LOGGING_DEBUG_COLOR='256'

# Statlog
# ------------------------------------------------
PLAN__STATLOG_GET_TAIL='true'
PLAN__STATLOG_TAB_LEN='1'
PLAN__STATLOG_SHOW_DIR='true'
PLAN__STATLOG_SHOW_INDEX='true'
PLAN__STATLOG_STICKY_INDEX='true'
PLAN__STATLOG_SPINNER='\ \ | | / / - -'
PLAN__STATLOG_SPINNER_COLOR='5'
PLAN__STATLOG_TITLE_COLOR='98'
PLAN__STATLOG_TAIL_COLOR='3'
PLAN__STATLOG_FAIL_ICON='-'
PLAN__STATLOG_FAIL_COLOR='1'
PLAN__STATLOG_OK_ICON='+'
PLAN__STATLOG_OK_COLOR='2'
PLAN__STATLOG_DIR_ICON=''
PLAN__STATLOG_DIR_COLOR='4'
PLAN__STATLOG_DIR_TITLE_COLOR='4'
PLAN__STATLOG_INDEX_L_COLOR='5'
PLAN__STATLOG_INDEX_R_COLOR='5'
PLAN__STATLOG_INDEX_BRACKET_L='('
PLAN__STATLOG_INDEX_BRACKET_R=')'
PLAN__STATLOG_INDEX_BRACKET_COLOR='5'
PLAN__STATLOG_INDEX_DIVIDER='/'
PLAN__STATLOG_INDEX_DIVIDER_COLOR='5'

# UI
# ------------------------------------------------
PLAN__UI_HR_CHAR='─'




