#!/usr/bin/env bash

WSE__VERSION='0.1.0'

#
# Planit Utils & Preconfig
#

pwd="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# We need to set this here to use Planit libs externally
PLAN__PATH_ROOT="${pwd}/planit"
source "${pwd}/planit/planit.conf"
source "${pwd}/planit.conf"
source "${pwd}/planit/lib/logging.sh" --component logger

path_modules="${pwd}/modules"
path_library="${pwd}/library"

declare -a modules
for path in "${path_modules}/"*; do
    modules+=("$path")
done

declare -A library
for path in "${path_library}/"*; do
    # Expects: 100_install_libname.sh, 100_[Install_LibName].sh, 100_[Install_LibName]
    library_name="${path##*_}"
    [[ "${path##*/}" = *\[*\]* ]] \
        && library_name="${library_name%%\]*}" \
        || library_name="${library_name%.*}"
    library["${library_name,,}"]="$path"
done

print_help() {
    cat << EOF
Usage: ${0##*/} [OPTIONS ...] [--] [MODULE_OPTIONS ...]

Workstation environment setup script. Running without any defined library
modules will install everything. For dynamic installation see --lib.
Installation is managed by the Planit framework.

Options:
  -l, --lib LIBRARY
              Comma-separated list of library modules to install. Each module
              will dynamically load its requirements for you. Omitting this
              option will lead to the installation of all modules.
  -L, --exclude LIBRARY
              Comma-separated list of library modules to exclude. This option
              overrides --lib and may cause issues with libraries that depend
              on excluded libraries. Use with caution.
  -R, --skip-required LIBRARY
              Comma-separated list of library modules to install without their
              dependencies. This will also prevent dependency chaining if
              LIBRARY itself was included as a dependency for another library.
  -s, --shell SHELL
              Comma-separated list of shells to configure. The installer will
              search for shell runtime configs (eg: .bashrc) and automatically
              configure them for use with installed libraries. This only works
              for a standard user install unless --force-root is passed.
              Compatible shells: bash, zsh
      --force-root
              Force installation as user 'root'. This is generally recommended
              against and may lead to an unstable install.
  -v, --version
              Print WS-Env version.
  -h, --help  Print this help message.

Example:
  ${0##*/} --shell bash,zsh
  ${0##*/} --shell bash --lib neovim,tmux --purge
  ${0##*/} --lib nerdfonts --nerdfonts-font jetbrainsmono,robotomono
EOF
}

#
# Parse Options
#

export WSE__SHELLS
force_root='false'
no_library='false'
skip_all_required='false'
declare -a skip_required
declare -a valid_shells=('bash' 'zsh')
declare -a exclude_targets
declare -A library_targets
declare -a _library_targets

while :; do
    case "$1" in
        --force-root) force_root='true' ;;
        -l | --lib)
            if [ -z "${2// /}" ]; then
                Plan::log.info 'Installing core modules only'
                no_library='true'
                shift
                continue
            fi
            IFS=, read -ra _library_targets <<< "$2"
            shift
            ;;
        -L | --exclude)
            IFS=, read -ra exclude_targets <<< "$2"
            Plan::log.info "Excluding modules: ${exclude_targets[*]}"
            shift
            ;;
        -R | --skip-required)
            IFS=, read -ra skip_required <<< "$2"
            if [[ " ${skip_required[*]} " = *' all '* ]]; then
                skip_all_required='true'
            fi
            ;;
        -s | --shell)
            declare -a shell_targets
            IFS=, read -ra shells <<< "$2"
            for sh in "${shells[@]}"; do
                if ! [[ " ${valid_shells[*]} " = *" $sh "* ]]; then
                    Plan::log.error "Invalid shell '$sh'; see --help"
                    exit 1
                fi
                shell_targets+=("$sh")
            done
            WSE__SHELLS="${shell_targets[*]}"
            shift
            ;;
        -h | --help)
            print_help
            exit 0
            ;;
        --)
            shift
            break
            ;;
        *) break ;;
    esac
    shift
done

add_library_target() {
    local target="$1"
    local target_path="${library["$target"]}"

    if ! [ -e "$target_path" ]; then
        Plan::log.error "Unknown library module '$target'"
        exit 1
    fi

    if [[ " ${exclude_targets[*]} " = *" $target "* ]]; then
        Plan::log.debug "Excluding library module '$target'"
        return 0
    elif [ -n "${library_targets[$target]}" ]; then
        Plan::log.debug "Skipping library module '$target' (duplicate)"
        return 0
    fi

    Plan::log.debug "Adding library module '$target'"
    library_targets["$target"]="$target_path"

    local -a required
    local req
    if [ -f "${target_path}/require.conf" ]; then
        read -d ' ' -ra required < <(cat "${target_path}/require.conf")
        if [ "$skip_all_required" = 'true' ] || [[ " ${skip_required[*]} " = *" $target "* ]]; then
            Plan::log.debug "Skipping '$target' dependencies: ${required[*]}"
            return 0
        fi
        for req in "${required[@]}"; do
            Plan::log.debug "Library module '$target' requires '$req'"
            add_library_target "$req"
        done
    fi
}

for target in "${_library_targets[@]}"; do
    add_library_target "$target"
done

if [ "${#library_targets[@]}" = '0' ] && [ "$no_library" != 'true' ]; then
    for target in "${!library[@]}"; do
        add_library_target "$target"
    done
fi

Plan::log.info "Installing libraries: ${!library_targets[*]}"

#
# Exit Handling
#

# We need to set the trap here before setting up caches and background procs.
# Also init the authentication process ID as this process (changed below).

declare WSE__AUTH_PID

exit_handler() {
    Plan::log.debug "Cleaning up '$module_cache'"
    rm -rf "$module_cache"
    kill -KILL "${WSE__AUTH_PID:-$$}" 2> /dev/null
}

trap 'exit_handler' EXIT INT TERM HUP QUIT

# auth_pid="$$"
# trap 'Plan::log.debug "Cleaning up \"$module_cache\""; rm -rf "$module_cache"; kill -KILL "$auth_pid" 2>/dev/null' \
#     EXIT INT TERM HUP QUIT

#
# Root Authentication
#

if [ "$(id -u)" = '0' ] && [ "$force_root" != 'true' ]; then
    Plan::log.error 'Attempting to run a root install requires --force-root'
    exit 1
elif ! sudo -n true 2> /dev/null; then
    Plan::log.info 'Installer requires an authenticated session'
    if ! sudo -v; then
        Plan::log.error "Failed to authenticate user '$USER'"
        exit 1
    fi
fi

while :; do
    sudo -v || break
    sleep 15
done &

WSE__AUTH_PID="$!"
Plan::log.debug "Sudo authentication process: $WSE__AUTH_PID"

#
# Distribution
#

if [ -f /etc/os-release ]; then
    source /etc/os-release
    WSE__DISTRIB="${ID,,}"
elif [ -f /etc/lsb-release ]; then
    source /etc/lsb-release
    WSE__DISTRIB="${DISTRIB_ID,,}"
else
    Plan::log.error 'Failed to determine system distribution'
    exit 1
fi

export WSE__DISTRIB
Plan::log.debug "System distribution '$WSE__DISTRIB'"

#
# Package Manager
#

if [ "$WSE__DISTRIB" = 'debian' ]; then
    pkg_update() { sudo apt update -y; }
    pkg_install() { sudo apt install -y "$@"; }
    pkg_remove() { sudo apt remove -y "$@"; }
elif [ "$WSE__DISTRIB" = 'fedora' ]; then
    pkg_update() { sudo dnf makecache --refresh; }
    pkg_install() { sudo dnf install -y "$@"; }
    pkg_remove() { sudo dnf remove -y "$@"; }
else
    Plan::log.error "Invalid distribution '$WSE__DISTRIB'"
    exit 1
fi

export -f pkg_update
export -f pkg_install
export -f pkg_remove

#
# Populate Module Cache
#

module_cache="${TEMPDIR:-/tmp}/wse.v${WSE__VERSION}.cache"
mkdir -p "$module_cache" || {
    Plan::log.error "Failed to create module cache '${module_cache}'"
    exit 1
}
Plan::log.debug "Module cache created '$module_cache'"

for path in "${modules[@]}"; do
    ln -s "$path" "${module_cache}/${path##*/}" || {
        Plan::log.error "Failed to cache core module '$path'"
        exit 1
    }
    Plan::log.debug "Core module cached '$path'"
done

if [ "${#library_targets[@]}" -gt 0 ]; then
    for target in "${!library_targets[@]}"; do
        path="${library_targets[$target]}"
        ln -s "$path" "${module_cache}/${path##*/}" || {
            Plan::log.error "Failed to cache library module '$path'"
            exit 1
        }
        Plan::log.debug "Library module cached '$path'"
    done
fi

#
# Environment: Functions
#

WSE::append_once() {
    local tag="$1" path="$2"
    shift 2
    lines="$*"
    local start_tag="# start=${tag}"
    local end_tag="# end=${tag}"
    ! grep -q "$start_tag" "$path" 2> /dev/null \
        && printf '\n%s\n%s\n%s\n' "$start_tag" "$lines" "$end_tag" >> "$path"
    return 0
}
export -f 'WSE::append_once'

WSE::git_download() {
    local name="$1" commit='' tag='' output=''
    shift
    while :; do
        case "$1" in
            -t | --tag)
                tag="$2"
                shift
                ;;
            -c | --commit)
                commit="$2"
                shift
                ;;
            -o | --output)
                output="$2"
                shift
                ;;
            '') break ;;
            *) exit 1 ;;
        esac
        shift
    done
    local repo="${name##*/}"
    local repo_url="https://github.com/${name}"
    output="${output:-$repo}"
    if [ -n "$tag" ]; then
        git clone --depth 1 -b "$tag" "$repo_url" "${output}" || return 1
    else
        git clone "$repo_url" "$output" || return 1
        if [ -n "$commit" ]; then
            (
                cd "$output"
                git checkout "$commit"
            ) || return 1
        fi
    fi
    return 0
}
export -f 'WSE::git_download'

#
# Environment: Variables
#

export WSE__GITHUB_API='https://api.github.com/repos'
export WSE__SHELLRCD="${HOME}/.shellrc.d"

#
# Shell Runtime Config
#

if [ -n "$WSE__SHELLS" ]; then
    Plan::log.debug "Configuring libraries for: $WSE__SHELLS"
    mkdir -p "$WSE__SHELLRCD" || exit 1
    IFS=' ' read -ra shells <<< "$WSE__SHELLS"
    for sh in "${shells[@]}"; do
        WSE::append_once 'shellrc' "${HOME}/.${sh}rc" \
            "for f in '${HOME}/.shellrc.d/'*; do " \
            '[ -f "$f" ] && ' \
            "[[ \"\$f\" =~ \\.(sh|${sh})\$ ]] && " \
            'source "$f"; ' \
            'done; ' \
            'unset f'
    done
fi

#
# Run Installer
#

"${pwd}/planit/planit" -m "${module_cache}" -- "$@"
