#!/usr/bin/env bash

#
# Planit Utils & Preconfig
#

pwd="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# We need to set this here to use Planit libs externally
PLAN__PATH_ROOT="${pwd}/planit"
source "${pwd}/planit/planit.conf"
source "${pwd}/planit.conf"
source "${pwd}/planit/lib/logging.sh" --component logger

path_modules="${pwd}/modules"
path_library="${pwd}/library"

declare -a modules
for path in "${path_modules}/"*; do
    modules+=("$path")
done

declare -A library
for path in "${path_library}/"*; do
    library_name="$(basename "$path")"
    library_name="${library_name#*_install_}"
    library["${library_name%.*}"]="$path"
done

print_help() {
    cat << EOF
Usage: ${0##*/} [OPTIONS ...] [--] [MODULE_OPTIONS ...]

Workstation environment setup script. Running without any defined library
modules will install everything. For dynamic installation see --lib.
Installation is managed by the Planit framework.

Options:
  -l, --lib TARGETS
              Comma-separated list of library modules to install. Each module
              will dynamically load its requirements for you. Omitting this
              option will lead to the installation of all modules.
  -s, --shell SHELL
              Comma-separated list of shells to configure. The installer will
              search for shell runtime configs (eg: .bashrc) and automatically
              configure them for use with installed libraries. This only works
              for a standard user install unless --force-root is passed.
              Compatible shells: bash, zsh
      --force-root
              Force installation as user 'root'. This is generally recommended
              against and may lead to an unstable install.
  -h, --help  Print this help message.

Example:
  ${0##*/} --shell bash,zsh
  ${0##*/} --shell bash --lib neovim,tmux
  ${0##*/} --lib nerdfonts -- --font jetbrainsmono,robotomono
EOF
}

#
# Parse Options
#

add_library_target() {
    local target="$1"
    local target_path="${library["$target"]}"
    if ! [ -e "$target_path" ]; then
        Plan::log.error "Unknown library module '$target'"
        exit 1
    fi
    if [ -z "${library_targets["$target"]}" ]; then
        Plan::log.debug "Adding library module '$target'"
        library_targets["$target"]="$target_path"
    else
        Plan::log.debug "Skipping library module '$target' (duplicate)"
        return 0
    fi
    local -a required
    local req
    if [ -f "${target_path}/require.conf" ]; then
        read -d ' ' -ra required < <(cat "${target_path}/require.conf")
        for req in "${required[@]}"; do
            Plan::log.debug "Library module '$target' requires '$req'"
            add_library_target "$req"
        done
    fi
}

export WSE__SHELLS
force_root='false'
no_library='false'
declare -a valid_shells=('bash' 'zsh')
declare -A library_targets

while :; do
    case "$1" in
        --force-root) force_root='true' ;;
        -l | --lib)
            IFS=, read -ra targets <<< "$2"
            for target in "${targets[@]}"; do
                add_library_target "$target"
            done
            if [ -z "${library_targets[*]}" ]; then
                Plan::log.info 'Installing core modules only'
                no_library='true'
            fi
            shift
            ;;
        -s | --shell)
            declare -a shell_targets
            IFS=, read -ra shells <<< "$2"
            for sh in "${shells[@]}"; do
                if ! [[ " ${valid_shells[*]} " = *" $sh "* ]]; then
                    Plan::log.error "Invalid shell '$sh'; see --help"
                    exit 1
                fi
                shell_targets+=("$sh")
            done
            WSE__SHELLS="${shell_targets[*]}"
            shift
            ;;
        -h | --help)
            print_help
            exit 0
            ;;
        --)
            shift
            break
            ;;
        *) break ;;
    esac
    shift
done

#
# Exit Handling
#

# We need to set the trap here before setting up caches and background procs.
# Also init the authentication process ID as this process (changed below).

auth_pid="$$"
trap 'Plan::log.debug "Cleaning up \"$module_cache\""; rm -rf "$module_cache"; kill -KILL "$auth_pid" 2>/dev/null' \
    EXIT INT TERM HUP QUIT

#
# Root Authentication
#

if [ "$(id -u)" = '0' ] && [ "$force_root" != 'true' ]; then
    Plan::log.error 'Attempting to run a root install requires --force-root'
    exit 1
elif ! sudo -n true 2> /dev/null; then
    Plan::log.info 'Installer requires an authenticated session'
    if ! sudo -v; then
        Plan::log.error "Failed to authenticate user '$USER'"
        exit 1
    fi
fi

while :; do
    sudo -v || break
    sleep 15
done &

auth_pid="$!"
Plan::log.debug "Sudo authentication process: $auth_pid"

#
# Distribution
#

if [ -f /etc/os-release ]; then
    source /etc/os-release
    WSE__DISTRIB="${ID,,}"
elif [ -f /etc/lsb-release ]; then
    source /etc/lsb-release
    WSE__DISTRIB="${DISTRIB_ID,,}"
else
    Plan::log.error 'Failed to determine system distribution'
    exit 1
fi

export WSE__DISTRIB
Plan::log.debug "System distribution '$WSE__DISTRIB'"

#
# Package Manager
#

if [ "$WSE__DISTRIB" = 'debian' ]; then
    pkg_update() { sudo apt update -y; }
    pkg_install() { sudo apt install -y "$@"; }
    pkg_remove() { sudo apt remove -y "$@"; }
elif [ "$WSE__DISTRIB" = 'fedora' ]; then
    pkg_update() { sudo dnf makecache --refresh; }
    pkg_install() { sudo dnf install -y "$@"; }
    pkg_remove() { sudo dnf remove -y "$@"; }
else
    Plan::log.error "Invalid distribution '$WSE__DISTRIB'"
    exit 1
fi

export -f pkg_update
export -f pkg_install
export -f pkg_remove

#
# Populate Module Cache
#

module_cache="$(mktemp -d)" || {
    Plan::log.error 'Failed to create module cache'
    exit 1
}
Plan::log.debug "Module cache created '$module_cache'"

for path in "${modules[@]}"; do
    ln -s "$path" "${module_cache}/${path##*/}" || {
        Plan::log.error "Failed to cache core module '$path'"
        exit 1
    }
    Plan::log.debug "Core module cached '$path'"
done

if [ "${#library_targets[@]}" -gt 0 ]; then
    for path in "${library_targets[@]}"; do
        ln -s "$path" "${module_cache}/${path##*/}" || {
            Plan::log.error "Failed to cache library module '$path'"
            exit 1
        }
        Plan::log.debug "Library module cached '$path'"
    done
elif [ "$no_library" != 'true' ]; then
    for path in "${library[@]}"; do
        ln -s "$path" "${module_cache}/${path##*/}" || {
            Plan::log.error "Failed to cache library module '$path'"
            exit
        }
        Plan::log.debug "Library module cached '$path'"
    done
fi

#
# Shell Runtime Config
#

WSE::append_once() {
    local tag="$1" path="$2"
    shift 2
    lines="$*"
    local start_tag="# start=${tag}"
    local end_tag="# end=${tag}"
    ! grep -q "$start_tag" "$path" 2> /dev/null \
        && printf '\n%s\n%s\n%s\n' "$start_tag" "$lines" "$end_tag" >> "$path"
    return 0
}
export -f 'WSE::append_once'

if [ -n "$WSE__SHELLS" ]; then
    Plan::log.debug "Configuring libraries for: $WSE__SHELLS"
    mkdir -p "${HOME}/.shellrc.d" || exit 1
    IFS=' ' read -ra shells <<< "$WSE__SHELLS"
    for sh in "${shells[@]}"; do
        mkdir -p "${HOME}/.shellrc.d/${sh}" || exit 1
        WSE::append_once 'shellrc' "${HOME}/.${sh}rc" \
            "for f in '${HOME}/.shellrc.d/${sh}/'*;" \
            'do [ -f "$f" ] && . "$f";' \
            'done;' \
            'unset f'
    done
fi

#
# Run Installer
#

"${pwd}/planit/planit" -m "${module_cache}" -- "$@"
