PLAN__STATE_ID='ws-env'
PLAN__MODULES_SYMLINKS='true'

PLAN__STATLOG_KEEP_TAIL='true'
PLAN__STATLOG_TAIL_FROM='STDMOD'

PLAN__ENABLE_CACHE='true'
PLAN__ENABLE_VCACHE='true'
PLAN__KEEP_CACHE='onfail'
PLAN__KEEP_VCACHE='onfail'
